# Generated by Django 3.2.3 on 2021-06-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newblog',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
